
name: Code coverage

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github 
        settings-path: ${{ github.workspace }} 

    - name: Run Coverage
      run: mvn verify

    - name: Upload Report
      uses: 'actions/upload-artifact@v4'
      with:
        name: report.xml
        path: ${{ github.workspace }}/target/jacoco-report/jacoco.xml

    - name: Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/target/jacoco-report/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 90
        min-coverage-changed-files: 90
        title: Code Coverage

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2.11.0
      with:
        generate-branches-badge: true
        jacoco-csv-file: target/jacoco-report/jacoco.csv

    - name: Commit and push the badge (if it changed)
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'commit badge'
        add: '*.svg'  

    - name: Get the Coverage info
      run: |
        echo "Total coverage: ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage: ${{ steps.jacoco.outputs.coverage-changed-files }}"
  
    - name: Fail PR if overall coverage is less than 90%
      if: ${{ steps.jacoco.outputs.coverage-overall < 90.0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Overall coverage is less than 90%!')
              
